@startuml UseCase_ChiTiet_DatLich
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor LightYellow
  BorderColor DarkSlateGray
}

actor "Bệnh nhân" as BN #LightBlue

rectangle "Phân hệ Đặt lịch khám" {
  usecase "Đặt lịch khám" as UC_MAIN #PaleGreen
  usecase "Xác thực người dùng\nqua JWT" as INC1
  usecase "Kiểm tra lịch\nlàm việc bác sĩ" as INC2
  usecase "Kiểm tra\ntrùng lịch hẹn" as INC3
  usecase "Kiểm tra dữ liệu\nđầu vào" as INC4
  usecase "Chọn hình thức\nthanh toán" as EXT1

  usecase "Hủy lịch hẹn" as UC_HUY #PaleGreen
  usecase "Kiểm tra quyền\nsở hữu" as INC5
  usecase "Kiểm tra trạng thái\ncho phép hủy" as INC6
}

BN -- UC_MAIN
BN -- UC_HUY

UC_MAIN ..> INC1 : <<include>>
UC_MAIN ..> INC2 : <<include>>
UC_MAIN ..> INC3 : <<include>>
UC_MAIN ..> INC4 : <<include>>
EXT1 ..> UC_MAIN : <<extend>>

UC_HUY ..> INC1 : <<include>>
UC_HUY ..> INC5 : <<include>>
UC_HUY ..> INC6 : <<include>>
@enduml
