@startuml SYS_SEQ_01_DangNhap
skinparam sequenceArrowThickness 1.5

mainframe sd SYS_SEQ_01_DangNhap

actor "Người dùng" as User
participant "Hệ thống" as Sys #SkyBlue
participant "Cơ sở dữ liệu" as DB #SkyBlue

User -> Sys : 1: Yêu cầu đăng nhập (email, password)
activate Sys

Sys -> DB : 1.1: Xác thực thông tin tài khoản
activate DB
DB --> Sys : 1.2: Trả về kết quả xác thực
deactivate DB

alt Hợp lệ
    Sys --> User : 1.3: Trả về token & thông tin cơ bản
else Sai thông tin
    Sys --> User : 1.4: Hiển thị thông báo lỗi đăng nhập
end

deactivate Sys

@enduml
